ServerEvents.recipes(event => {
    //Create
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:shaft'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:cogwheel'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:large_cogwheel'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:gearbox'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:vertical_gearbox'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:encased_chain_drive'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:adjustable_chain_gearshift'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:clutch'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:turntable'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:chain_conveyor'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:depot'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:weighted_ejector'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:create:item_vault'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:linear_chassis'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:secondary_linear_chassis'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:radial_chassis'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:cuckoo_clock'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:windmill_bearing'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:mechanical_bearing'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:rope_pulley'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:sticker'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:mechanical_piston'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:sticky_mechanical_piston'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:piston_extension_pole'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:gantry_carriage'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:gantry_shaft'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:speedometer'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:stressometer'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:cart_assembler'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:belt_connector'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:fluid_pipe'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:mechanical_pipe'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:fluid_valve'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:copper_valve_handle'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:fluid_tank'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:hose_pulley'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:item_drain'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:spout'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:portable_fluid_interface'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:steam_engine'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create:steam_whistle'})

    //Create: Connected
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create_connected:encased_chain_cogwheel'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create_connected:inverted_clutch'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create_connected:inverted_gearshift'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create_connected:parallel_gearbox'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create_connected:vertical_parallel_gearbox'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create_connected:six_way_gearbox'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create_connected:vertical_six_way_gearbox'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create_connected:cross_connector'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create_connected:shear_pin'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create_connected:overstress_clutch'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create_connected:centrifugal_clutch'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create_connected:freewheel_clutch'})
    event.remove({ not: { type: 'minecraft:stonecutting'}, output: 'create_connected:brake'})

})