ServerEvents.recipes(event => {
    //Create
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:gearbox' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:vertical_gearbox' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:encased_chain_drive' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:adjustable_chain_gearshift' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:clutch' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:turntable' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:chain_conveyor' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:depot' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:weighted_ejector' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:item_vault' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:linear_chassis' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:secondary_linear_chassis' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:radial_chassis' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:cuckoo_clock' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:windmill_bearing' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:mechanical_bearing' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:rope_pulley' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:sticker' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:mechanical_piston' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:sticky_mechanical_piston' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:piston_extension_pole' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:gantry_carriage' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:gantry_shaft' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:speedometer' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:stressometer' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:cart_assembler' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:belt_connector' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:fluid_pipe' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:mechanical_pump' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:fluid_valve' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:copper_valve_handle' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:fluid_tank' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:hose_pulley' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:item_drain' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:spout' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:portable_fluid_interface' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:steam_engine' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:steam_whistle' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:chute' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:hand_crank' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:mechanical_drill' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:mechanical_saw' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:mechanical_plough' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:mechanical_harvester' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:basin' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:mechanical_roller' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:mechanical_press' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:mechanical_mixer' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:millstone' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:encased_fan' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:andesite_funnel' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:andesite_tunnel' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:mechanical_roller' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:basin' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:mechanical_press' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:mechanical_mixer' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:millstone' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:encased_fan' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:packager' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:package_frogport' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:stock_link' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:stock_ticker' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:redstone_requester' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:redstone_contact' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:redstone_link' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:analog_lever' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:powered_latch' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create:powered_toggle_latch' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'minecraft:redstone_torch' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'minecraft:repeater' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'minecraft:comparator' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'quark:redstone_randomizer' })

    //Create: Connected
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_connected:encased_chain_cogwheel' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_connected:inverted_clutch' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_connected:inverted_gearshift' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_connected:parallel_gearbox' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_connected:vertical_parallel_gearbox' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_connected:six_way_gearbox' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_connected:vertical_six_way_gearbox' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_connected:cross_connector' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_connected:shear_pin' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_connected:overstress_clutch' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_connected:centrifugal_clutch' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_connected:freewheel_clutch' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_connected:brake' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_connected:fluid_vessel' })

    //Create: Factory Logistics
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_factory_logistics:jar_packager' })

    //Create: Enchantment Industry
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_enchantment_industry:disenchanter' })
    event.remove({ not: { type: 'minecraft:stonecutting' }, output: 'create_enchantment_industry:printer' })

})